version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "8080:8080"

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env.dev

    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://postgres:password@host.docker.internal:5433/mydb_app"
