name: Lint

on:
  push:
  pull_request:

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend dependencies
        working-directory: ./src/frontend
        run: npm ci

      - name: Run ESLint Front End
        working-directory: ./src/frontend
        run: npm run lint

  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend dependencies
        working-directory: ./src/backend
        run: npm ci

      - name: Run ESLint Back End
        working-directory: ./src/backend
        run: npm run lint
