server {
    listen 80;
    listen [::]:80;

    # Use localhost for local development or yourdomain.com www.yourdomain.com;
    server_name localhost;

    # Serve the built React files
    root /usr/share/nginx/html;
    index index.html;

    # Send unknown routes to index.html so React Router can handle them
    location / {
        try_files $uri $uri/ /index.html;
    }
}